### PR TITLE
Added support for tags sup and sub.

### PR DESCRIPTION
**Pull request by javadev**
html code
```html
<code>una <sup>vuelta</sup></code> de <sub>molinillo</sub> de <sup>pimienta</sup>
```

will be converter to markdown
```
<code>una <sup>vuelta</sup></code> de <sub>molinillo</sub> de <sup>pimienta</sup>
```

### CODE REVIEW

**Comment by furstenheim** [comment]
Hi Valentin, thanks for the contribution.

You are missing some tests in src/test/resources/tests.json. Try also to add some tests where the content inside sub has to be escaped.

However, before that, is <code> really a markdown thing? I don't see it in the documentation: https://www.markdownguide.org/extended-syntax/

I do see however, some support for subscript and superscript, H~2~O and X^2^. But, for example github does not support that.

**Comment by javadev** [comment]
Hi @furstenheim.

Thank you for your message.

I am not very experienced in unit testing. I suggest to merge this pr and add more tests latter.

I will check other text modifications in markdown.

**Comment by javadev** [comment]
I found a description for sup and sub.

image

**Comment by furstenheim** [comment]
Hi @javadev, I'm sorry but I won't be merging anything without proper tests. As I mentioned before, I'm not sure that the code component is something in markdown.

**Comment by javadev** [comment]
X^2 I tested this syntaxis. Only this is supposed X<sup>2</sup>. I agree this is for github.

**Pull request closed without merging**
